apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    name: mlflow
---
# Role for MLflow
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlflow-role
  namespace: mlflow
rules:
  - apiGroups: ["" ]
    resources: ["pods", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["" ]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlflow-role-binding
  namespace: mlflow
subjects:
  - kind: ServiceAccount
    name: mlflow
    namespace: mlflow
roleRef:
  kind: Role
  name: mlflow-role
  apiGroup: rbac.authorization.k8s.io
