apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts
  namespace: mlflow
  labels:
    app: mlflow
    component: artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: efs-sc
  selector:
    matchLabels:
      app: mlflow
      component: artifacts
