apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
    component: service-account
---
# Image Pull Secret
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: mlflow
  annotations:
    kubernetes.io/service-account.name: mlflow
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-registry-credentials>
