version: "3.9"

services:
  multirole:
    build:
      context: ./multirole
    image: multirole-server
    container_name: multirole
    ports:
      - "7922:7922"
      - "7911:7911"
      - "34343:34343"
      - "62672:62672"
      - "49382:49382"
      - "43632:43632"
    volumes:
      - ../../decks/known:/multirole/decks
      - ./replays:/multirole/replays
    networks:
      - duelnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 7922"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  windbot_a:
    build:
      context: ./windbot
    depends_on:
      multirole:
        condition: service_healthy
    volumes:
      - ../../decks/known:/windbot-source/Decks
    environment:
      DECK: "2021_goat_format_deck"
    networks:
      - duelnet

  windbot_b:
    build:
      context: ./windbot
    depends_on:
      multirole:
        condition: service_healthy
    volumes:
      - ../../decks/known:/windbot-source/Decks
    environment:
      DECK: "2023_Dragunity"
    networks:
      - duelnet

networks:
  duelnet:
    driver: bridge
