version: '3.8'

services:
  edopro:
    image: edopro-assets
    container_name: edopro
    ports:
      - "7911:7911"  # EDOPro listens on this port
    networks:
      - yugioh-net
    command: >
      sh -c "sleep 3 && xvfb-run -a ./EDOPro -p 7911 -i-want-to-be-admin -l duel.log"

  windbot-1:
    image: windbot
    container_name: windbot-1
    depends_on:
      - edopro
    environment:
      SERVER_MODE: "false"
      WIND_HOST: edopro
      WIND_PORT: 7911
      DECK_FILE: "/windbot/Decks/a.ydk"
      BOT_NAME: "AI_1"
      EXPORT_PATH: "/GameData"
      HAND: "2"
      IS_TRAINING: "true"
      SHOULD_UPDATE: "true"
      SHOULD_RECORD: "false"
      IS_MCTS: "true"
    volumes:
      - ./gamelogs/ai_1:/GameData
    networks:
      - yugioh-net

  windbot-2:
    image: windbot
    container_name: windbot-2
    depends_on:
      - edopro
    environment:
      SERVER_MODE: "false"
      WIND_HOST: edopro
      WIND_PORT: 7911
      DECK_FILE: "/windbot/Decks/b.ydk"
      BOT_NAME: "AI_2"
      EXPORT_PATH: "/GameData"
      HAND: "3"
      IS_TRAINING: "true"
      SHOULD_UPDATE: "true"
      SHOULD_RECORD: "false"
      IS_MCTS: "false"
    volumes:
      - ./gamelogs/ai_2:/GameData
    networks:
      - yugioh-net

networks:
  yugioh-net:
    driver: bridge


