version: '3.8'

services:
  ygopro-server:
    build:
      context: ./ygopro
    container_name: ygopro-server
    ports:
      - "7911:7911"
    networks:
      - yugioh-net
    command:
      - bash
      - -exc
      - |
        echo "Launching Xvfb on :99";
        Xvfb :99 -screen 0 640x480x24 &
        export DISPLAY=:99
        echo "Starting YGOPro on DISPLAY=$DISPLAY";
        ./bin/release/YGOPro \
          -n HostBot \
          -p 7911 \
          -k \
          -c
 
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 7911 || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10

  windbot-1:
    build:
      context: ./windbot
    container_name: windbot-1
    # depends_on:
    #   ygopro-server:
    #     condition: service_healthy
    environment:
      WIND_HOST: ygopro-server
      WIND_PORT: 7911
      DECK_FILE: "/windbot/Decks/a.ydk"
      BOT_NAME: "AI_1"
      EXPORT_PATH: "/GameData"
      HAND: "2"
      IS_TRAINING: "true"
      SHOULD_UPDATE: "true"
      SHOULD_RECORD: "false"
      IS_MCTS: "true"
    volumes:
      - ./gamelogs/ai_1:/GameData
    networks:
      - yugioh-net

  windbot-2:
    build:
      context: ./windbot
    container_name: windbot-2
    # depends_on:
    #   ygopro-server:
    #     condition: service_healthy
    environment:
      WIND_HOST: ygopro-server
      WIND_PORT: 7911
      DECK_FILE: "/windbot/Decks/b.ydk"
      BOT_NAME: "AI_2"
      EXPORT_PATH: "/GameData"
      HAND: "3"
      IS_TRAINING: "true"
      SHOULD_UPDATE: "true"
      SHOULD_RECORD: "false"
      IS_MCTS: "false"
    volumes:
      - ./gamelogs/ai_2:/GameData
    networks:
      - yugioh-net

networks:
  yugioh-net:
    driver: bridge



