version: "3.9"

services:
  windbot_a:
    build:
      context: ./windbot
    depends_on:
      multirole:
        condition: service_healthy
    environment:
      DECK_FILE: "/windbot/Decks/2021_goat_format_deck.ydk"
      SERVER_MODE: "true"
      WIND_HOST: "multirole"
      WIND_PORT: "7911"
      BOT_NAME: "WindBot"
    networks:
      - duelnet
    ports:
      - "2399:2399"

  windbot_b:
    build:
      context: ./windbot
    depends_on:
      windbot_a:
        condition: service_started
    environment:
      DECK_FILE: "/windbot/Decks/2023_Dragunity.ydk"
      SERVER_MODE: "false"
      WIND_HOST: "multirole"
      WIND_PORT: "7911"
      BOT_NAME: "OpponentBot"
    networks:
      - duelnet

  trigger_duel:
    image: curlimages/curl:latest
    depends_on:
      windbot_a:
        condition: service_started
    entrypoint: >
      sh -c "sleep 5 && curl 'http://windbot_a:2399/?name=2021_goat_format_deck&host=127.0.0.1&port=7911'"
    networks:
      - duelnet

networks:
  duelnet:
    driver: bridge

