name: Pull Raw Yugioh Data - Monthly

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

  push:
    branches:
      - setup_data_action

jobs:
  pull_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
          -f src/data_pull_api/Dockerfile \
          -t yugioh-data-pull .

      - name: Run Docker container
        run: |
          docker run --rm \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          yugioh-data-pull